CREATE TABLE  white_list (
  id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userid VARCHAR(100) NOT NULL,
  ips VARCHAR(255) NOT NULL COMMENT '白名單ips (ex: 192.168.50.0/24, 35.201.204.77)',
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP );
 