import errors from './index'

const ERRORS = {
  InvalidSignature: { restCode: 1, message: 'Invalid Signature', statusCode: 403 },
  InvalidMerchantCode: { restCode: 2, message: 'Invalid Merchant Code', statusCode: 403 },
  InvalidSecureKey: { restCode: 3, message: 'Invalid Secure Key', statusCode: 403 },
  InvalidAuthToken: { restCode: 4, message: 'Invalid Auth Token', statusCode: 403 },
  InvalidGamePlatformId: { restCode: 5, message: 'Invalid Platform Id', statusCode: 403 },
  InvalidUsername: { restCode: 6, message: 'Invalid Username', statusCode: 400 },
  InvalidPassword: { restCode: 7, message: 'Invalid Password', statusCode: 400 },
  DuplicateUsername: { restCode: 8, message: 'Duplicate Username', statusCode: 400 },
  InvalidExtraInfo: { restCode: 9, message: 'Invalid Extra Info', statusCode: 400 },
  InvalidGamePlatformSettings: { restCode: 10, message: 'Invalid Game Platform Settings', statusCode: 400 },
  InvalidBetLimit: { restCode: 11, message: 'Invalid Bet Limit', statusCode: 400 },
  InvalidActionType: { restCode: 12, message: 'Invalid Action Type', statusCode: 400 },
  InvalidAmount: { restCode: 13, message: 'Invalid Amount', statusCode: 400 },
  DuplicateExternalTransId: { restCode: 14, message: 'Duplicate External Transaction Id', statusCode: 400 },
  NoEnoughBalance: { restCode: 15, message: 'No Enough Balance', statusCode: 400 },
  InvalidFromDateTime: { restCode: 16, message: 'Invalid From Date Time', statusCode: 400 },
  InvalidToDateTime: { restCode: 17, message: 'Invalid To Date Time', statusCode: 400 },
  InvalidExternalTransId: { restCode: 18, message: 'Invalid External Transaction Id', statusCode: 400 },
  SecureKeyNotAllowed: { restCode: 19, message: 'SecureKey Not Allowed', statusCode: 400 },
  BonusRequired: { restCode: 20, message: 'Bonus Required', statusCode: 400 },
  InvalidBonus: { restCode: 21, message: 'Invalid Bonus', statusCode: 400 },
  InvalidRebate: { restCode: 22, message: 'Invalid Rebate', statusCode: 400 },
  AccountDuplicated: { restCode: 23, message: 'Sub account duplicated', statusCode: 400 },
  SubAccountNotFound: { restCode: 24, message: 'Sub account not found', statusCode: 404 },
  InvalidParent: { restCode: 25, message: 'Invalid parent username', statusCode: 400 },
  UnhandledRejection: 500,
  ValidationFailed: 400,
  PlayerNotFound: 404,
  AddWalletFailed: 400,
  PendWalletFailed: 400,
  GenerateMerchantFailed: 400,
  GeneratePlayerFailed: 400,
  UpdateMerchantFailed: 400,
  MerchantDuplicated: 400,
  InvalidRole: 400,
  InvalidGames: 400,
  InvalidAgency: 400,
  InvalidCurrency: 400,
  TransferFailed: 400,
  GameNotFound: 404,
  GamePeriodDuplicated: 400,
  TerminatePeriodFailed: 400,
  InvalidGamePeriod: 400,
  PermissionDenied: 403,
  BetNotFound: 404,
  BetFailed: 400,
  RefundBetFailed: 400,
  RefundChaseFailed: 400,
  ChaseFailed: 400,
  ChaseNotFound: 404,
  InvalidBetNumber: 400,
  InvalidPeriod: 400,
  BetLocked: 400,
  GamePeriodNotFound: 404,
  CreatePlayerFailed: 400,
  PlayerDuplicated: 400,
  ParserInvalid: 400,
  ChangePasswordFailed: 400,
  InvalidProfit: 400,
  ResetPasswordFailed: 400,
  SaveMissingPeriodFailed: 400,
  UpdateMissingPeriodFailed: 400,
  SavePeriodVerifyResultFailed: 400,
  AddWarningFailed: 400,
  InvalidGameRule: 400,
  InvalidGame: 400,
  LotteryOpened: 400,
  PrivateLotteryOpened: 400,
  CustomPrivateLotteryOpened: 400,
  InvalidOddsGame: 400,
  InvalidOddsCount: 400,
  PeriodCountRequired: 400,
  SaveContractFailed: 400,
  CreateSubAccountFailed: 400,
  UpdateSubAccountFailed: 400,
  DeleteSubAccountFailed: 400,
  BannerRequired: 400,
  LogoRequired: 400,
  BillsNotFound: 404,
  AccountDeleted: 400,
  BillsAccountingFailed: 400,
  InvalidCommissionGame: 400,
  InvalidCommissionValue: 400,
  CreateTemplateFailed: 400,
  UpdateTemplateFailed: 400,
  DeleteTemplateFailed: 400,
  TemplateNotFound: 404,
  InvalidAgentChild: 400,
  InvalidAgentBonus: 400,
  InvalidAgentAgency: 400,
  InvalidAgentRebate: 400,
  InvalidAgentSalary: 400,
  InvalidBetAmount: 400,
  InvalidBillsAmount: 400,
  InvalidBillsStatus: 400,
  InvalidBillsFeeMode: 400,
  InvalidExchangeRate: 400,
  BalanceExceeded: 400,
  WechatUserAuthFailed: 400,
  InvalidGameUrl: 400,
  SignupFailed: 400,
  RebateRequired: 400,
  UpdateWechatFailed: 400,
  LinkPlayerFailed: 400,
  CreateOrderFailed: 400,
  PasswordNotChanged: 400,
  WrongPassword: 400,
  GetMessageFailed: 400,
  SendMessageFailed: 400,
  InvalidBetFormat: 400,
  DomainDuplicated: 400,
  AddDomainFailed: 400,
  UpdateDomainFailed: 400,
  DeleteDomainFailed: 400,
  EcValidationFaile: 400,
  SaveNextOpenCodeFailed: 400,
  PrivateOpenLotteryFailed: 400,
  InvalidOpenCode: 400,
  PayoutRageRequired: 400,
  PayoutRageForbidden: 400,
  CreateScopeFailed: 400,
  UpdateScopeFailed: 400,
  DeleteScopeFailed: 400,
  ScopeNotFound: 404,
  InvalidSalary: 400,
  ParentRequired: 400,
  ScopeNotEmpty: 400,
  ChaseNowAllowed: 400,
  BeyoundChaseMax: 400,
  CreateAgentLinkFailed: 400,
  AddBankAccFailed: 400,
  InvalidAssetPasswordFormat: 400,
  SameAsPlayerPassword: 400,
  CreateAssetPasswordFailed: 400,
  AlreadyHasAssetPassword: 400,
  WrongOldAssetPassword: 400,
  NewAssetPasswordIsTheSameAsOld: 400,
  AssetPasswordNotFound: 404,
  UpdateAssetPasswordFailed: 400,
  AlreadySetSecurityQA: 400,
  InvalidQuestionIds: 400,
  EmptyAnswer: 400,
  CreateSecurityQAFailed: 400,
  SecurityQANotFound: 404,
  SecureQATokenRequired: 400,
  CannotAddMoreThanFiveAccs: 400,
  BankAccIsUsed: 400,
  UpdateBankAccFailed: 400,
  BankRecordNotFound: 404,
  AccountDetailNotFound: 404,
  CredentialNotFound: 404,
  IncorrectAccountToBeDeleted: 400,
  DeleteBankAccountFailed: 400,
  InvalidOrderStatus: 400,
  InvalidQuestionId: 400,
  QuestionExpired: 400,
  GatewayOperFailed: 400,
  AddPayMerchantFailed: 400,
  OnePayMerchantAllowed: 400,
  PayMerchantDuplicated: 400,
  UpdatePayMerchantFailed: 400,
  CompanyRequired: 400,
  PayPlatformDuplicated: 400,
  InvalidPayChannel: 400,
  GetDepositUrlFailed: 400,
  InvalidOrderInfo: 400,
  OrderNotFound: 404,
  UpdateFailedAttemptFailed: 400,
  UpdateAuthBlockFailed: 400,
  BindGatewayPlayerFailed: 400,
  SaveGatewayBindingFailed: 400,
  CompanyNotFound: 404,
  PayChannelDuplicated: 400,
  UpdateBindingAuthFailed: 400,
  GetGatewayAuthTokenFailed: 400,
  InvalidGamePeriodTime: 400,
  WithdrawFailed: 400,
  AddNewPrefixFailed: 400,
  AuthStatusIsNotAllowed: 400,
  InvalidQAToken: 400,
  CreateClearanceFailed: 400,
  ResetPWAnswerExccedAllowedTimes: 400,
  TokenExpired: 400,
  UpdateClearanceFailed: 400,
  ResetLoginPasswordFailed: 400,
  GetPlayerSaltFailed: 400,
  GatewayUsernamePrefixNotEnough: 400,
  WithdrawHandled: 400,
  WithdrawNotFound: 404,
  InvalidGTData: 400,
  WithdrawNotAllowed: 400,
  CreateAnnouncementFailed: 400,
  DeleteAnnouncementFailed: 400,
  AnnouncementNotFound: 404,
  NotUnderSameCompany: 400,
  LoopParent: 400,
  MoveAgentFailed: 400,
  InvalidSrcRole: 400,
  InvalidDesRole: 400,
  CompanyCannotHavePlayer: 400,
  MovingMaster: 400,
  NoNeedToMove: 400,
  InvalidVipLevel: 400,
  InvalidVipAmount: 400,
  CreatePromotionFailed: 400,
  UpdatePromotionFailed: 400,
  PromotionNotFound: 404,
  NoEnoughValidBalance: 400,
  OrderTooOften: 400,
  InvalidDividendValue: 400,
  InvalidMaxDividendValue: 400,
  InvalidAvgBetAmount: 400,
  InvalidBetPlayerCount: 400,
  DividendLayerNeeded: 400,
  OnlyAgentAllowed: 400,
  InvalidDividendPlayer: 400,
  InvalidSalaryGap: 400,
  InvalidSalaryLayer: 400,
  SalaryValueRequired: 400,
  SalaryNotDivisibleByFive: 400,
  InvalidSalaryValue: 400,
  SalaryUpperLimitExceeded: 400,
  InvalidSalaryBetAmount: 400,
  InvalidSalaryPlayerCount: 400,
  InvalidSalaryRank: 400,
  SalaryLayerRequired: 400,
  AddTagFailed: 400,
  BankNotSupported: 400,
  NoValidWithdrawPlatform: 400,
  WalletNotFound: 404,
  TagDuplicated: 400,
  UpdateDefaultBankAccFailed: 400,
  CannotDeleteDefaultAccount: 400,
  InvalidRecordId: 400,
  LotteryVerifyFailed: 400,
  SetDefaultBankAccFailed: 400,
  InvalidPlayerSummaryParam: 400,
  GetFailedAttemptFailed: 400,
  FollowPlayerFailed: 400,
  PromotionInactive: 400,
  ApplyPromotionFailed: 400,
  PromotionAttendLimitReached: 400,
  PromotionAttendIntervalNotAchieved: 400,
  PromotionApplyNotFound: 404,
  PromotionApplyHandled: 400,
  HandlePromotionApplyFailed: 400,
  AlreadyFollowing: 400,
  InvalidDomain: 400,
  ReviewPromotionFailed: 400,
  InvalidPromotionAction: 400,
  PromotionApplyNotReached: 400,
  InvalidUpdatePromotionStatus: 400,
  SubmitPromotionFailed: 400,
  StartPromotionFailed: 400,
  EndPromotionFailed: 400,
  CancelPromotionFailed: 400,
  PromotionMonopolistic: 400,
  PromotionTotalAttendLimitReached: 400,
  InvalidAwardContent: 400,
  AccumulatedPromotionEndTimeRequired: 400,
  SaveGameGatewayFailed: 400,
  GameGatewayCompanyDuplicated: 400,
  GameGatewayMerchantCodeDuplicated: 400,
  GameGatewayPrefixDuplicated: 400,
  PaybusMerchantRequired: 400,
  InvalidDefaultBonus: 400
}

errors.register(ERRORS)
